### ISSUE TITLE
CakePHP3対応

### ISSUE THREAD

**Issue by hampom** [uluru/anti_bounce#5]
CakePHP3に対応しました:tada:

もしよろしければ、取り込んで頂きたいのでCakePHP3用のブランチをご用意いただけませんか？
PRさせていただきもす

**Comment by t-maehira** [comment]
大変ありがたいです！
PR楽しみにしております:pray:

**Comment by t-maehira** [comment]
@hampom 
https://github.com/uluru/anti_bounce/tree/CakePHP3.x
こちらに準備させていただきました！
PRよろしくお願い致します。
